version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: carcompare_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: carcompare
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: