import { SafetyFeatures, ComfortFeatures, AestheticFeatures } from '@/types/car.types';

export const SAFETY_LABELS: Record<keyof SafetyFeatures, string> = {
    abs: "Système ABS",
    esp: "Contrôle de trajectoire (ESP)",
    airbags: "Airbags multiples",
    tractionControl: "Antipatinage",
    emergencyBraking: "Aide au Freinage d'Urgence",
    immobilizer: "Antidémarrage électronique",
    hillStartAssist: "Aide au démarrage en côte",
    fatigueDetection: "Détection de fatigue",
    laneAssist: "Maintien dans la voie",
    blindSpotMonitor: "Détecteur d'angle mort",
    tirePressureMonitor: "Détecteur de sous-gonflage",
    autoDoorLock: "Fermeture de portes auto.",
    isofix: "Fixations ISOFIX",
    fogLights: "Phares antibrouillard",
    alarm: "Système d'alarme",
    trafficSignRecognition: "Reconnaissance des panneaux",
};

export const COMFORT_LABELS: Record<keyof ComfortFeatures, string> = {
    airConditioning: "Climatisation",
    audioSystem: "Système audio",
    onBoardComputer: "Ordinateur de bord",
    startStop: "Start & Stop",
    cruiseControl: "Régulateur de vitesse",
    rainSensor: "Détecteur de pluie",
    autoHeadlights: "Allumage auto. des feux",
    electricParkingBrake: "Frein à main électrique",
    touchScreen: "Ecran tactile",
    digitalCockpit: "Cockpit digital",
    headUpDisplay: "Affichage Tête-Haute",
    rearCamera: "Caméra de recul",
    parkingSensors: "Aide au stationnement",
    parkAssist: "Park Assist Auto.",
    steeringWheelControls: "Commandes au volant",
    voiceCommands: "Commandes vocales",
    adjustableSteeringWheel: "Volant réglable",
    electricWindows: "Vitres électriques",
    electricMirrors: "Rétros. électriques",
    foldingMirrors: "Rétros. rabattables électriques",
    electricTrunk: "Coffre électrique",
    keylessEntry: "Mains libres (Démarrage)",
    electricSeats: "Sièges électriques",
    memorySeats: "Sièges élec. avec mémoire",
    foldingRearSeats: "Banquette arrière rabattable",
    navigationGps: "Navigation GPS",
    wifi: "WiFi à bord",
    bluetooth: "Bluetooth",
    appleCarplay: "Apple CarPlay",
    androidAuto: "Android Auto",
    wirelessCharging: "Chargeur/mobile sans fil",
    steeringPaddles: "Palettes au volant",
};

export const AESTHETIC_LABELS: Record<keyof AestheticFeatures, string> = {
    alloyWheels: "Jantes aluminium",
    upholstery: "Sellerie",
    leatherSteeringWheel: "Volant cuir",
    followMeHome: "Follow-me home",
    ambientLighting: "Lumière d'ambiance",
    daytimeRunningLights: "Feux de jour",
    headlights: "Phares",
    roof: "Toit",
    roofRails: "Barres de toit",
    tintedWindows: "Vitres sur-teintées",
};
